### ISSUE TITLE
Compiled problem crystal 0.31.1

### ISSUE THREAD

**Issue by bglobalnet** [splattael/hashids.cr#3]
Hi,

Installed the crystal version 0.31.1, but when I compile the code I received this error:

883 | hash = hashids.encode([theId])
                      ^-----
Error: instantiating 'Hashids#encode(Array(Int32))'

In lib/hashids/src/hashids.cr:30:5

 30 | _encode(numbers)
      ^------
Error: instantiating '_encode(Array(Int32))'

In lib/hashids/src/hashids.cr:72:14

 72 | last = _to_alphabet(number, alphabet)
             ^-----------
Error: instantiating '_to_alphabet(Int32, String)'

In lib/hashids/src/hashids.cr:169:5

 169 | loop do
       ^---
Error: instantiating 'loop()'

In lib/hashids/src/hashids.cr:169:5

 169 | loop do
       ^---
Error: instantiating 'loop()'

In lib/hashids/src/hashids.cr:170:21

 170 | id << alphabet[input % alphabet.size]
                     ^
Error: no overload matches 'String#[]' with type (Float64 | Int32)

Overloads are:
 - String#[](start : Int, count : Int)
 - String#[](regex : Regex, group)
 - String#[](index : Int)
 - String#[](range : Range)
 - String#[](str : String | Char)
 - String#[](regex : Regex)
Couldn't find overloads for these types:
 - String#[](Float64)

Thank you,

**Comment by bdtomlin** [comment]
I have made some changes that make this closer to a port of the ruby version and it also working with Crystal 0.32.1. @splattael, it's certainly not perfect, but it works and the test suite passes.

I don't have a lot of time right now and may come back to refactor in the future. If you want to take a look and are interested in a PR, just let me know. https://github.com/bdtomlin/hashids.cr

**Comment by splattael** [comment]
@bdtomlin Thanks! Sure a PR would be awesome so we can discuss how this PR improves the code/performance :+1: 

Getting closer to the Ruby version is great, BTW!

**Comment by splattael** [comment]
Closing :+1: 

Thanks again @bdtomlin

**Comment by bdtomlin** [comment]
@splattael Thanks for merging, and creating this library. It has been crucial for my Lucky framework app.

**Comment by splattael** [comment]
Thank YOU for contributing :+1: and please excuse the delay :disappointed:
